### ISSUE TITLE
Missing csv/dataset files

### ISSUE THREAD

**Issue by asigalov61** [PatricioGuinle/CoffeMIDI#2]
Hey Patricio,

I was trying to run the web code/flask...and it seems that it is missing a few files...

#df_scaled = pd.read_csv('df_scaled.csv',sep=",",index_col='indice')
#data_index = pd.read_csv('data_index.csv',sep=",",index_col='indice.1')

Are you going to make them available?

Thank you.

Alex

**Comment by PatricioGuinle** [comment]
Hi Alex,

I just shared them with you by drive to your email

let me know any other questions

Regards,

Patricio

**Comment by asigalov61** [comment]
Thank you for your prompt response and help.

I did not get a drive email yet. Please check if it went through.

Alex
________________________________

**Comment by PatricioGuinle** [comment]
we solved by email.
Just closing issue here
